name: pr-test
on: pull_request

env:
  DB_PASSWORD: root
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  pr-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Start Redis
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: 6

      - name: Start Mysql Service
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE shoppingtest;' -uroot -proot

      - name: Set up JDK 21
        uses: actions/setup-java@main
        with:
          java-version: '21'
          cache: 'gradle'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.5

      - name: Run Test
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper
          arguments: test
          # gradle test -> admin, user모두
          # 멀티모듈 user, admin 모듈이 분리
          # arguments: user:test admin:test

      - name: send slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: GitHub Actions
          fields: repo,commit,author,ref,workflow,job,took
        if: always()